In [1]:
'''
Trevor Kleinstuber
'''

import os
import pandas as pd

In [2]:
directory = '../Cleaned Data/'
files = os.listdir(directory)

In [3]:
data_files = []
for file in files:
    if file[-4:] == '.csv':
        data_files.append(file)
        
data_files

['clean_energy_consumption_data.csv',
 'disasters.csv',
 'population_density_clean.csv',
 'Temperature_Delta_1986 to 2016.csv']

In [4]:
data_dfs = []
for data_file in data_files:
    data_dfs.append(
        pd.read_csv(directory + data_file)
    )
    print(data_file)
    
for df in data_dfs:
    print(df.columns, '\n\n', df.size)

clean_energy_consumption_data.csv
disasters.csv
population_density_clean.csv
Temperature_Delta_1986 to 2016.csv
Index(['Unnamed: 0', 'Location', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016'],
      dtype='object')

 38082
Index(['Year', 'Disaster Type', 'Country', 'ISO', 'Start Year', 'End Year',
       'Total Deaths', 'Total Affected', 'Total Damages ('000 US$)'],
      dtype='object')

 139671
Index(['Country Name', 'Country Code', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016'],
      dtype='object')

 8250
Index(['Unnamed: 0', 'Source', 'Year', 'Mean'], dtype='object')

 296

In [5]:
def trim(string):
    return string.strip()
for index, row in data_dfs[0].iterrows():
    row['Location'] = row['Location'].strip()
    
data_dfs[0].Location = data_dfs[0].Location.map(trim)
data_dfs[0]

,Unnamed: 0,Location,1986,1987,1988,1989,1990,1991,1992,1993,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,0,World,324.5344016,334.5932663,347.6354523,352.3576472,358.9595455,352.2644272,351.0744285,353.9732567,...,493.091062,499.6972405,494.3132499,523.725112,538.7016471,550.8484054,561.7706158,567.0296292,570.0615279,573.9508257
1,1,Afghanistan,0.039111199,0.063065158,0.111220787,0.109364539,0.108320341,0.047438198,0.031281766,0.031068733,...,0.034254709,0.058526483,0.095348795,0.118538529,0.161050802,0.147607649,0.124017682,0.113619521,0.125483137,0.117133389
2,2,Albania,0.166075365,0.166640543,0.168590876,0.160340585,0.114845298,0.096323694,0.084191203,0.073833402,...,0.09682504,0.105744823,0.115070874,0.128327344,0.105875204,0.104431132,0.127732976,0.116326405,0.116576406,0.12436058
3,3,Algeria,1.073661264,1.148639374,1.222947634,1.18021525,1.212354841,1.354444964,1.30211942,1.197210337,...,1.558107806,1.68592524,1.783379231,1.777793483,1.938981898,2.099941293,2.039276069,2.30202481,2.354764812,2.337093871
4,4,American Samoa,0.006716584,0.006973009,0.006778814,0.007806191,0.008210538,0.008210538,0.008445519,0.008216196,...,0.008606956,0.008630536,0.008606956,0.008606956,0.004911509,0.004924966,0.004911509,0.004911509,0.004908811,0.004908869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,1153,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1150,1154,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1151,1155,Yemen,0,0,0,0,0,0,0,0,...,0,0,0,0.000019512,0.000019432,0.000028548,0.000047705,0.0000951,0.001081004,0.00143096
1152,1156,Zambia,0.09076501,0.081980147,0.080546524,0.064865504,0.075368102,0.07546398,0.074200986,0.073979034,...,0.09416468,0.093821618,0.094043332,0.099505352,0.11139352,0.114221132,0.122657277,0.128670644,0.119663804,0.106261164
1153,1157,Zimbabwe,0.0425037,0.029455262,0.031615066,0.040564523,0.045798166,0.042218631,0.036289722,0.024696334,...,0.060089685,0.057708724,0.054348202,0.055831638,0.048768864,0.050187342,0.048011757,0.049817875,0.044750116,0.034072702

In [6]:
consumption_countries = data_dfs[0].Location.unique()
consumption_countries

array(['World', 'Afghanistan', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burma', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo-Brazzaville',
       'Congo-Kinshasa', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Côte d’Ivoire', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Falkland Islands', 'Faroe Islands',
       'Fiji', 'Finland', 'Former Czechoslovakia',
       'Former Serbia and Montenegro', 'Former U.S.S.R.',
       'Former Yugoslavia', 'France', 'French Guiana', 'French Polynesia',
       'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Germany, East',
       'Germany, West', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Hawaiian Trade Zone',
       'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macau',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia',
       'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco',
       'Mozambique', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Korea',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palestinian Territories', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent/Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'The Bahamas', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'U.S. Pacific Islands',
       'U.S. Territories', 'U.S. Virgin Islands', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wake Island', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe',
       'Northern Mariana Islands'], dtype=object)

In [7]:
density_countries = data_dfs[2]['Country Name'].unique()
density_countries

array(['Aruba', 'Afghanistan', 'Angola', 'Albania', 'Andorra',
       'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antigua and Barbuda', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Benin', 'Burkina Faso', 'Bangladesh',
       'Bulgaria', 'Bahrain', 'Bahamas, The', 'Bosnia and Herzegovina',
       'Belarus', 'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados',
       'Brunei Darussalam', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada',
       'Central Europe and the Baltics', 'Switzerland', 'Channel Islands',
       'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica',
       'Caribbean small states', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.',
       'Euro area', 'Spain', 'Estonia', 'Ethiopia', 'European Union',
       'Fragile and conflict affected situations', 'Finland', 'Fiji',
       'France', 'Faroe Islands', 'Gabon', 'United Kingdom', 'Georgia',
       'Ghana', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'Guam', 'Guyana', 'High income', 'Hong Kong SAR, China',
       'Honduras', 'Heavily indebted poor countries (HIPC)', 'Croatia',
       'Haiti', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total',
       'IDA blend', 'Indonesia', 'IDA only', 'Isle of Man', 'India',
       'Ireland', 'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel',
       'Italy', 'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya',
       'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'St. Kitts and Nevis',
       'Korea, Rep.', 'Latin America & Caribbean (excluding high income)',
       'Lao PDR', 'Lebanon', 'Liberia', 'Libya', 'St. Lucia',
       'Latin America & Caribbean',
       'Least developed countries: UN classification', 'Low income',
       'Liechtenstein', 'Sri Lanka', 'Lower middle income',
       'Low & middle income', 'Lesotho', 'Late-demographic dividend',
       'Lithuania', 'Latvia', 'Macao SAR, China',
       'St. Martin (French part)', 'Morocco', 'Monaco', 'Moldova',
       'Madagascar', 'Maldives', 'Middle East & North Africa', 'Mexico',
       'Middle income', 'North Macedonia', 'Mali', 'Malta', 'Myanmar',
       'Middle East & North Africa (excluding high income)', 'Montenegro',
       'Mongolia', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi',
       'Malaysia', 'North America', 'Namibia', 'New Caledonia', 'Niger',
       'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru',
       'New Zealand', 'OECD members', 'Oman', 'Other small states',
       'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea',
       'Poland', 'Pre-demographic dividend', 'Puerto Rico',
       'Korea, Dem. People’s Rep.', 'Portugal', 'Paraguay',
       'Pacific island small states', 'Post-demographic dividend',
       'French Polynesia', 'Qatar', 'Romania', 'Russian Federation',
       'Rwanda', 'South Asia', 'Saudi Arabia', 'Senegal', 'Singapore',
       'Solomon Islands', 'Sierra Leone', 'El Salvador', 'San Marino',
       'Somalia', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa', 'Small states', 'Sao Tome and Principe',
       'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini',
       'Seychelles', 'Syrian Arab Republic', 'Turks and Caicos Islands',
       'Chad', 'East Asia & Pacific (IDA & IBRD countries)',
       'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand',
       'Tajikistan', 'Turkmenistan',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)',
       'Tonga', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Tuvalu', 'Tanzania', 'Uganda', 'Ukraine',
       'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan',
       'St. Vincent and the Grenadines', 'Venezuela, RB',
       'British Virgin Islands', 'Virgin Islands (U.S.)', 'Vietnam',
       'Vanuatu', 'World', 'Samoa', 'Kosovo', 'Yemen, Rep.',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [8]:

def Diff(li1, li2): 
    '''
    # Python code t get difference of two lists 
    # Using set() 
    '''
    return (list(set(li1).symmetric_difference(set(li2))))

In [9]:
delta = Diff(consumption_countries, density_countries)
delta

['Macau',
 'Cook Islands',
 'Early-demographic dividend',
 'Eritrea',
 'Saint Lucia',
 'Myanmar',
 'East Asia & Pacific (excluding high income)',
 'Saint Vincent/Grenadines',
 'Heavily indebted poor countries (HIPC)',
 'Syrian Arab Republic',
 'Small states',
 'Sub-Saharan Africa',
 'Korea, Dem. People’s Rep.',
 'Martinique',
 'Niue',
 'Brunei',
 'Western Sahara',
 'Liechtenstein',
 "Cote d'Ivoire",
 'Montserrat',
 'Luxembourg',
 'Hong Kong SAR, China',
 'Post-demographic dividend',
 'Arab World',
 'South Asia (IDA & IBRD)',
 'Iran, Islamic Rep.',
 'Germany, East',
 'French Guiana',
 'Europe & Central Asia',
 'Taiwan',
 'Fragile and conflict affected situations',
 'Netherlands Antilles',
 'Iran',
 'Channel Islands',
 'South Sudan',
 'Andorra',
 'Syria',
 'Yemen, Rep.',
 'High income',
 'Sub-Saharan Africa (excluding high income)',
 'Former U.S.S.R.',
 'Reunion',
 'Russian Federation',
 'Serbia',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Lao PDR',
 'Middle East & North Africa',
 'Euro area',
 'St. Vincent and the Grenadines',
 'IDA only',
 'Central Europe and the Baltics',
 'Least developed countries: UN classification',
 'Former Yugoslavia',
 'Venezuela',
 'Wake Island',
 'Saint Kitts and Nevis',
 'Saint Pierre and Miquelon',
 'East Asia & Pacific',
 'Caribbean small states',
 'Kyrgyz Republic',
 'Low & middle income',
 'Europe & Central Asia (IDA & IBRD countries)',
 'IDA blend',
 'South Asia',
 'U.S. Pacific Islands',
 'Macao SAR, China',
 'Côte d’Ivoire',
 'Lower middle income',
 'Hong Kong',
 'Kuwait',
 'Micronesia',
 'St. Kitts and Nevis',
 'Yemen',
 'Falkland Islands',
 'The Bahamas',
 'San Marino',
 'Former Czechoslovakia',
 'Low income',
 'North Korea',
 'Other small states',
 'Virgin Islands (U.S.)',
 'Northern Mariana Islands',
 'Guadeloupe',
 'U.S. Virgin Islands',
 'Kyrgyzstan',
 'Upper middle income',
 'Middle income',
 'U.S. Territories',
 'Congo-Brazzaville',
 'Russia',
 'Slovakia',
 'Hawaiian Trade Zone',
 'Late-demographic dividend',
 'Monaco',
 'Belgium',
 'Latin America & Caribbean (excluding high income)',
 'Saint Helena',
 'St. Martin (French part)',
 'St. Lucia',
 'Venezuela, RB',
 'North America',
 'Isle of Man',
 'Brunei Darussalam',
 'Congo, Rep.',
 'IBRD only',
 'Congo-Kinshasa',
 'Congo, Dem. Rep.',
 'Middle East & North Africa (IDA & IBRD countries)',
 'Pacific island small states',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Laos',
 'Pre-demographic dividend',
 'Egypt, Arab Rep.',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Europe & Central Asia (excluding high income)',
 'Egypt',
 'Burma',
 'Former Serbia and Montenegro',
 'Antarctica',
 'Latin America & Caribbean',
 'OECD members',
 'IDA total',
 'Slovak Republic',
 'Middle East & North Africa (excluding high income)',
 'Curacao',
 'Germany, West',
 'European Union',
 'Korea, Rep.',
 'South Korea',
 'Bahamas, The',
 'IDA & IBRD total',
 'Palestinian Territories',
 'Sudan']

In [10]:
'''
what questions do we want to answer?
'''

'\nwhat questions do we want to answer?\n'

In [11]:
import difflib

In [12]:
possible_duplicates = []
for thing in delta:
    matches = difflib.get_close_matches(thing, delta)
    if len(matches) > 1:
        #print(matches)
        possible_duplicates.append(matches)

In [13]:
pos_dup = []
for group in possible_duplicates:
    group.sort()
    
possible_duplicates.sort()
for group in possible_duplicates:
    if not (group in pos_dup):
        pos_dup.append(group)
pos_dup

[['Bahamas, The', 'The Bahamas'],
 ['Caribbean small states',
  'Other small states',
  'Pacific island small states'],
 ['Caribbean small states', 'Other small states', 'Small states'],
 ['Caribbean small states', 'Pacific island small states'],
 ['Channel Islands', 'Cook Islands', 'Wake Island'],
 ['Channel Islands', 'Falkland Islands', 'Wake Island'],
 ['Congo, Dem. Rep.', 'Congo, Rep.'],
 ['Congo, Dem. Rep.', 'Congo, Rep.', 'Yemen, Rep.'],
 ['Congo, Rep.', 'Korea, Rep.', 'Yemen, Rep.'],
 ["Cote d'Ivoire", 'Côte d’Ivoire'],
 ['Early-demographic dividend',
  'Late-demographic dividend',
  'Pre-demographic dividend'],
 ['East Asia & Pacific',
  'East Asia & Pacific (IDA & IBRD countries)',
  'East Asia & Pacific (excluding high income)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Middle East & North Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (excluding high income)',
  'Europe & Central Asia (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['East Asia & Pacific (excluding high income)',
  'Latin America & Caribbean (excluding high income)',
  'Middle East & North Africa (excluding high income)'],
 ['East Asia & Pacific (excluding high income)',
  'Latin America & Caribbean (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['East Asia & Pacific (excluding high income)',
  'Middle East & North Africa (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['Eritrea', 'Euro area'],
 ['Europe & Central Asia',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Europe & Central Asia (excluding high income)'],
 ['Europe & Central Asia (IDA & IBRD countries)',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['Europe & Central Asia (excluding high income)',
  'Middle East & North Africa (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['Former Czechoslovakia', 'Former Yugoslavia'],
 ['Germany, East', 'Germany, West'],
 ['High income', 'Low income', 'Middle income'],
 ['Hong Kong', 'Hong Kong SAR, China'],
 ['Hong Kong', 'Hong Kong SAR, China', 'Macao SAR, China'],
 ['Hong Kong SAR, China', 'Macao SAR, China'],
 ['IBRD only', 'IDA only'],
 ['IBRD only', 'IDA only', 'IDA total'],
 ['IDA & IBRD total', 'IDA only', 'IDA total'],
 ['IDA & IBRD total', 'IDA total'],
 ['Korea, Dem. People’s Rep.', 'Korea, Rep.'],
 ['Kyrgyz Republic', 'Slovak Republic', 'Syrian Arab Republic'],
 ['Late-demographic dividend',
  'Post-demographic dividend',
  'Pre-demographic dividend'],
 ['Latin America & Caribbean',
  'Latin America & Caribbean (excluding high income)',
  'Latin America & the Caribbean (IDA & IBRD countries)'],
 ['Low & middle income', 'Low income', 'Lower middle income'],
 ['Low & middle income', 'Lower middle income', 'Middle income'],
 ['Low & middle income', 'Lower middle income', 'Upper middle income'],
 ['Lower middle income', 'Middle income', 'Upper middle income'],
 ['Middle East & North Africa',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Middle East & North Africa (excluding high income)'],
 ['North America', 'North Korea', 'South Asia'],
 ['North America', 'North Korea', 'South Korea'],
 ['North Korea', 'South Asia', 'South Korea'],
 ['Palestinian Territories', 'U.S. Territories'],
 ['Saint Helena', 'Saint Lucia'],
 ['Saint Helena', 'Saint Lucia', 'St. Lucia'],
 ['Saint Kitts and Nevis', 'St. Kitts and Nevis'],
 ['Saint Lucia', 'St. Lucia'],
 ['Saint Vincent/Grenadines', 'St. Vincent and the Grenadines'],
 ['Serbia', 'Syria'],
 ['Slovak Republic', 'Slovakia'],
 ['Slovak Republic', 'Slovakia', 'Syrian Arab Republic'],
 ['South Asia',
  'South Asia (IDA & IBRD)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['South Asia', 'South Korea', 'South Sudan'],
 ['South Sudan', 'Sudan'],
 ['Sub-Saharan Africa',
  'Sub-Saharan Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (excluding high income)'],
 ['U.S. Pacific Islands', 'U.S. Virgin Islands'],
 ['U.S. Pacific Islands', 'U.S. Virgin Islands', 'Virgin Islands (U.S.)'],
 ['U.S. Virgin Islands', 'Virgin Islands (U.S.)'],
 ['Venezuela', 'Venezuela, RB'],
 ['Yemen', 'Yemen, Rep.']]

In [14]:
# duplicates = []
# for group in possible_duplicates:
#     print(group)
#     if input('Are theses similar?').lower()[0] == 'y':
#         duplicates.append(group)

In [15]:
def slst_has_bad(lst, bad):
    '''
    finds if any string in a list contains and string in the list of strings bad
    '''
    for string in lst:
        for bad_string in bad:
            if string.find(bad_string) > -1:
                return True
        
    return False
    
dirty = ['&', 'income', 'dividend', 'only', 'total']
trash = [group for group in pos_dup if slst_has_bad(group, dirty)]
clean = [group for group in pos_dup if not slst_has_bad(group, dirty)]
            
trash

[['Early-demographic dividend',
  'Late-demographic dividend',
  'Pre-demographic dividend'],
 ['East Asia & Pacific',
  'East Asia & Pacific (IDA & IBRD countries)',
  'East Asia & Pacific (excluding high income)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Middle East & North Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Latin America & the Caribbean (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (IDA & IBRD countries)',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['East Asia & Pacific (excluding high income)',
  'Europe & Central Asia (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['East Asia & Pacific (excluding high income)',
  'Latin America & Caribbean (excluding high income)',
  'Middle East & North Africa (excluding high income)'],
 ['East Asia & Pacific (excluding high income)',
  'Latin America & Caribbean (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['East Asia & Pacific (excluding high income)',
  'Middle East & North Africa (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['Europe & Central Asia',
  'Europe & Central Asia (IDA & IBRD countries)',
  'Europe & Central Asia (excluding high income)'],
 ['Europe & Central Asia (IDA & IBRD countries)',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['Europe & Central Asia (excluding high income)',
  'Middle East & North Africa (excluding high income)',
  'Sub-Saharan Africa (excluding high income)'],
 ['High income', 'Low income', 'Middle income'],
 ['IBRD only', 'IDA only'],
 ['IBRD only', 'IDA only', 'IDA total'],
 ['IDA & IBRD total', 'IDA only', 'IDA total'],
 ['IDA & IBRD total', 'IDA total'],
 ['Late-demographic dividend',
  'Post-demographic dividend',
  'Pre-demographic dividend'],
 ['Latin America & Caribbean',
  'Latin America & Caribbean (excluding high income)',
  'Latin America & the Caribbean (IDA & IBRD countries)'],
 ['Low & middle income', 'Low income', 'Lower middle income'],
 ['Low & middle income', 'Lower middle income', 'Middle income'],
 ['Low & middle income', 'Lower middle income', 'Upper middle income'],
 ['Lower middle income', 'Middle income', 'Upper middle income'],
 ['Middle East & North Africa',
  'Middle East & North Africa (IDA & IBRD countries)',
  'Middle East & North Africa (excluding high income)'],
 ['South Asia',
  'South Asia (IDA & IBRD)',
  'Sub-Saharan Africa (IDA & IBRD countries)'],
 ['Sub-Saharan Africa',
  'Sub-Saharan Africa (IDA & IBRD countries)',
  'Sub-Saharan Africa (excluding high income)']]

In [16]:
clean

[['Bahamas, The', 'The Bahamas'],
 ['Caribbean small states',
  'Other small states',
  'Pacific island small states'],
 ['Caribbean small states', 'Other small states', 'Small states'],
 ['Caribbean small states', 'Pacific island small states'],
 ['Channel Islands', 'Cook Islands', 'Wake Island'],
 ['Channel Islands', 'Falkland Islands', 'Wake Island'],
 ['Congo, Dem. Rep.', 'Congo, Rep.'],
 ['Congo, Dem. Rep.', 'Congo, Rep.', 'Yemen, Rep.'],
 ['Congo, Rep.', 'Korea, Rep.', 'Yemen, Rep.'],
 ["Cote d'Ivoire", 'Côte d’Ivoire'],
 ['Eritrea', 'Euro area'],
 ['Former Czechoslovakia', 'Former Yugoslavia'],
 ['Germany, East', 'Germany, West'],
 ['Hong Kong', 'Hong Kong SAR, China'],
 ['Hong Kong', 'Hong Kong SAR, China', 'Macao SAR, China'],
 ['Hong Kong SAR, China', 'Macao SAR, China'],
 ['Korea, Dem. People’s Rep.', 'Korea, Rep.'],
 ['Kyrgyz Republic', 'Slovak Republic', 'Syrian Arab Republic'],
 ['North America', 'North Korea', 'South Asia'],
 ['North America', 'North Korea', 'South Korea'],
 ['North Korea', 'South Asia', 'South Korea'],
 ['Palestinian Territories', 'U.S. Territories'],
 ['Saint Helena', 'Saint Lucia'],
 ['Saint Helena', 'Saint Lucia', 'St. Lucia'],
 ['Saint Kitts and Nevis', 'St. Kitts and Nevis'],
 ['Saint Lucia', 'St. Lucia'],
 ['Saint Vincent/Grenadines', 'St. Vincent and the Grenadines'],
 ['Serbia', 'Syria'],
 ['Slovak Republic', 'Slovakia'],
 ['Slovak Republic', 'Slovakia', 'Syrian Arab Republic'],
 ['South Asia', 'South Korea', 'South Sudan'],
 ['South Sudan', 'Sudan'],
 ['U.S. Pacific Islands', 'U.S. Virgin Islands'],
 ['U.S. Pacific Islands', 'U.S. Virgin Islands', 'Virgin Islands (U.S.)'],
 ['U.S. Virgin Islands', 'Virgin Islands (U.S.)'],
 ['Venezuela', 'Venezuela, RB'],
 ['Yemen', 'Yemen, Rep.']]

In [22]:
totally_clean = []
for group in clean:
    print(group)
    if input('Do these cantain multiple strings with the same meaning? ').lower()[0] == 'y':
        print('')
#         if input('Do any of these items have a different meaning?').lower()[0] == 'y':
#             try:
#                 index = input('Which index (0,1,2...)?')
#                 group.pop(int(index))
#             except ValueError:
#                 # Handle the exception
#                 print('Please enter an integer')
#             except IndexError:
#                 print('value must be in range')
        #else: trash.c
    else: 
        trash.append(clean.pop(clean.index(group)))
        
clean

['Bahamas, The', 'The Bahamas']
Do these cantain multiple strings with the same meaning? y

['Other small states', 'Small states']
Do these cantain multiple strings with the same meaning? y

['Congo, Dem. Rep.', 'Congo, Rep.']
Do these cantain multiple strings with the same meaning? y

["Cote d'Ivoire", 'Côte d’Ivoire']
Do these cantain multiple strings with the same meaning? y

['Germany, East', 'Germany, West']
Do these cantain multiple strings with the same meaning? y

['Hong Kong', 'Hong Kong SAR, China']
Do these cantain multiple strings with the same meaning? y

['Korea, Dem. People’s Rep.', 'Korea, Rep.']
Do these cantain multiple strings with the same meaning? y

['North Korea', 'South Asia', 'South Korea']
Do these cantain multiple strings with the same meaning? n
['Saint Kitts and Nevis', 'St. Kitts and Nevis']
Do these cantain multiple strings with the same meaning? y

['Saint Lucia', 'St. Lucia']
Do these cantain multiple strings with the same meaning? y

['Saint Vincent/Grenadines', 'St. Vincent and the Grenadines']
Do these cantain multiple strings with the same meaning? y

['Slovak Republic', 'Slovakia']
Do these cantain multiple strings with the same meaning? y

['South Sudan', 'Sudan']
Do these cantain multiple strings with the same meaning? y

['U.S. Virgin Islands', 'Virgin Islands (U.S.)']
Do these cantain multiple strings with the same meaning? y

['Venezuela', 'Venezuela, RB']
Do these cantain multiple strings with the same meaning? y

['Yemen', 'Yemen, Rep.']
Do these cantain multiple strings with the same meaning? y

[['Bahamas, The', 'The Bahamas'],
 ['Other small states', 'Small states'],
 ['Congo, Dem. Rep.', 'Congo, Rep.'],
 ["Cote d'Ivoire", 'Côte d’Ivoire'],
 ['Germany, East', 'Germany, West'],
 ['Hong Kong', 'Hong Kong SAR, China'],
 ['Korea, Dem. People’s Rep.', 'Korea, Rep.'],
 ['Saint Lucia', 'St. Lucia'],
 ['Saint Kitts and Nevis', 'St. Kitts and Nevis'],
 ['Saint Lucia', 'St. Lucia'],
 ['Saint Vincent/Grenadines', 'St. Vincent and the Grenadines'],
 ['Slovak Republic', 'Slovakia'],
 ['South Sudan', 'Sudan'],
 ['U.S. Virgin Islands', 'Virgin Islands (U.S.)'],
 ['Venezuela', 'Venezuela, RB'],
 ['Yemen', 'Yemen, Rep.']]

In [23]:
dupes = pd.DataFrame(clean)

In [24]:
dupes

                            0                               1
0                Bahamas, The                     The Bahamas
1          Other small states                    Small states
2            Congo, Dem. Rep.                     Congo, Rep.
3               Cote d'Ivoire                   Côte d’Ivoire
4               Germany, East                   Germany, West
5                   Hong Kong            Hong Kong SAR, China
6   Korea, Dem. People’s Rep.                     Korea, Rep.
7                 Saint Lucia                       St. Lucia
8       Saint Kitts and Nevis             St. Kitts and Nevis
9                 Saint Lucia                       St. Lucia
10   Saint Vincent/Grenadines  St. Vincent and the Grenadines
11            Slovak Republic                        Slovakia
12                South Sudan                           Sudan
13        U.S. Virgin Islands           Virgin Islands (U.S.)
14                  Venezuela                   Venezuela, RB
15                      Yemen                     Yemen, Rep.

In [25]:
dupes.to_csv('../Cleaned Data/duplicated_spellings.csv',index=False)