In [1]:
'''
Trevor Kleinstuber
'''

import os
import pandas as pd

In [2]:
directory = '../Cleaned Data/'
files = os.listdir(directory)

In [3]:
data_files = []
for file in files:
    if file[-4:] == '.csv':
        data_files.append(file)
        
data_files

['clean_energy_consumption_data.csv',
 'disasters.csv',
 'population_density_clean.csv',
 'Temperature_Delta_1986 to 2016.csv']

In [4]:
data_dfs = []
for data_file in data_files:
    data_dfs.append(
        pd.read_csv(directory + data_file)
    )
    print(data_file)
    
for df in data_dfs:
    print(df.columns, '\n\n', df.size)

clean_energy_consumption_data.csv
disasters.csv
population_density_clean.csv
Temperature_Delta_1986 to 2016.csv
Index(['Unnamed: 0', 'Location', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016'],
      dtype='object')

 38082
Index(['Year', 'Disaster Type', 'Country', 'ISO', 'Start Year', 'End Year',
       'Total Deaths', 'Total Affected', 'Total Damages ('000 US$)'],
      dtype='object')

 139671
Index(['Country Name', 'Country Code', '1986', '1987', '1988', '1989', '1990',
       '1991', '1992', '1993', '1994', '1995', '1996', '1997', '1998', '1999',
       '2000', '2001', '2002', '2003', '2004', '2005', '2006', '2007', '2008',
       '2009', '2010', '2011', '2012', '2013', '2014', '2015', '2016'],
      dtype='object')

 8250
Index(['Unnamed: 0', 'Source', 'Year', 'Mean'], dtype='object')

 296

In [5]:
def trim(string):
    return string.strip()
for index, row in data_dfs[0].iterrows():
    row['Location'] = row['Location'].strip()
    
data_dfs[0].Location = data_dfs[0].Location.map(trim)
data_dfs[0]

,Unnamed: 0,Location,1986,1987,1988,1989,1990,1991,1992,1993,...,2007,2008,2009,2010,2011,2012,2013,2014,2015,2016
0,0,World,324.5344016,334.5932663,347.6354523,352.3576472,358.9595455,352.2644272,351.0744285,353.9732567,...,493.091062,499.6972405,494.3132499,523.725112,538.7016471,550.8484054,561.7706158,567.0296292,570.0615279,573.9508257
1,1,Afghanistan,0.039111199,0.063065158,0.111220787,0.109364539,0.108320341,0.047438198,0.031281766,0.031068733,...,0.034254709,0.058526483,0.095348795,0.118538529,0.161050802,0.147607649,0.124017682,0.113619521,0.125483137,0.117133389
2,2,Albania,0.166075365,0.166640543,0.168590876,0.160340585,0.114845298,0.096323694,0.084191203,0.073833402,...,0.09682504,0.105744823,0.115070874,0.128327344,0.105875204,0.104431132,0.127732976,0.116326405,0.116576406,0.12436058
3,3,Algeria,1.073661264,1.148639374,1.222947634,1.18021525,1.212354841,1.354444964,1.30211942,1.197210337,...,1.558107806,1.68592524,1.783379231,1.777793483,1.938981898,2.099941293,2.039276069,2.30202481,2.354764812,2.337093871
4,4,American Samoa,0.006716584,0.006973009,0.006778814,0.007806191,0.008210538,0.008210538,0.008445519,0.008216196,...,0.008606956,0.008630536,0.008606956,0.008606956,0.004911509,0.004924966,0.004911509,0.004911509,0.004908811,0.004908869
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1149,1153,Wake Island,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1150,1154,Western Sahara,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1151,1155,Yemen,0,0,0,0,0,0,0,0,...,0,0,0,0.000019512,0.000019432,0.000028548,0.000047705,0.0000951,0.001081004,0.00143096
1152,1156,Zambia,0.09076501,0.081980147,0.080546524,0.064865504,0.075368102,0.07546398,0.074200986,0.073979034,...,0.09416468,0.093821618,0.094043332,0.099505352,0.11139352,0.114221132,0.122657277,0.128670644,0.119663804,0.106261164
1153,1157,Zimbabwe,0.0425037,0.029455262,0.031615066,0.040564523,0.045798166,0.042218631,0.036289722,0.024696334,...,0.060089685,0.057708724,0.054348202,0.055831638,0.048768864,0.050187342,0.048011757,0.049817875,0.044750116,0.034072702

In [6]:
consumption_countries = data_dfs[0].Location.unique()
consumption_countries

array(['World', 'Afghanistan', 'Albania', 'Algeria', 'American Samoa',
       'Angola', 'Antarctica', 'Antigua and Barbuda', 'Argentina',
       'Armenia', 'Aruba', 'Australia', 'Austria', 'Azerbaijan',
       'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium',
       'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brazil',
       'British Virgin Islands', 'Brunei', 'Bulgaria', 'Burkina Faso',
       'Burma', 'Burundi', 'Cabo Verde', 'Cambodia', 'Cameroon', 'Canada',
       'Cayman Islands', 'Central African Republic', 'Chad', 'Chile',
       'China', 'Colombia', 'Comoros', 'Congo-Brazzaville',
       'Congo-Kinshasa', 'Cook Islands', 'Costa Rica', 'Croatia', 'Cuba',
       'Cyprus', 'Czech Republic', 'Côte d’Ivoire', 'Denmark', 'Djibouti',
       'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Falkland Islands', 'Faroe Islands',
       'Fiji', 'Finland', 'Former Czechoslovakia',
       'Former Serbia and Montenegro', 'Former U.S.S.R.',
       'Former Yugoslavia', 'France', 'French Guiana', 'French Polynesia',
       'Gabon', 'Gambia, The', 'Georgia', 'Germany', 'Germany, East',
       'Germany, West', 'Ghana', 'Gibraltar', 'Greece', 'Greenland',
       'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guinea',
       'Guinea-Bissau', 'Guyana', 'Haiti', 'Hawaiian Trade Zone',
       'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India',
       'Indonesia', 'Iran', 'Iraq', 'Ireland', 'Israel', 'Italy',
       'Jamaica', 'Japan', 'Jordan', 'Kazakhstan', 'Kenya', 'Kiribati',
       'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon',
       'Lesotho', 'Liberia', 'Libya', 'Lithuania', 'Luxembourg', 'Macau',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Martinique', 'Mauritania', 'Mauritius', 'Mexico', 'Micronesia',
       'Moldova', 'Mongolia', 'Montenegro', 'Montserrat', 'Morocco',
       'Mozambique', 'Namibia', 'Nauru', 'Nepal', 'Netherlands',
       'Netherlands Antilles', 'New Caledonia', 'New Zealand',
       'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North Korea',
       'North Macedonia', 'Norway', 'Oman', 'Pakistan',
       'Palestinian Territories', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Peru', 'Philippines', 'Poland', 'Portugal',
       'Puerto Rico', 'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda',
       'Saint Helena', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Pierre and Miquelon', 'Saint Vincent/Grenadines', 'Samoa',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Suriname', 'Sweden',
       'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania',
       'Thailand', 'The Bahamas', 'Timor-Leste', 'Togo', 'Tonga',
       'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan',
       'Turks and Caicos Islands', 'Tuvalu', 'U.S. Pacific Islands',
       'U.S. Territories', 'U.S. Virgin Islands', 'Uganda', 'Ukraine',
       'United Arab Emirates', 'United Kingdom', 'United States',
       'Uruguay', 'Uzbekistan', 'Vanuatu', 'Venezuela', 'Vietnam',
       'Wake Island', 'Western Sahara', 'Yemen', 'Zambia', 'Zimbabwe',
       'Northern Mariana Islands'], dtype=object)

In [7]:
density_countries = data_dfs[2]['Country Name'].unique()
density_countries

array(['Aruba', 'Afghanistan', 'Angola', 'Albania', 'Andorra',
       'Arab World', 'United Arab Emirates', 'Argentina', 'Armenia',
       'American Samoa', 'Antigua and Barbuda', 'Australia', 'Austria',
       'Azerbaijan', 'Burundi', 'Benin', 'Burkina Faso', 'Bangladesh',
       'Bulgaria', 'Bahrain', 'Bahamas, The', 'Bosnia and Herzegovina',
       'Belarus', 'Belize', 'Bermuda', 'Bolivia', 'Brazil', 'Barbados',
       'Brunei Darussalam', 'Bhutan', 'Botswana',
       'Central African Republic', 'Canada',
       'Central Europe and the Baltics', 'Switzerland', 'Channel Islands',
       'Chile', 'China', "Cote d'Ivoire", 'Cameroon', 'Congo, Dem. Rep.',
       'Congo, Rep.', 'Colombia', 'Comoros', 'Cabo Verde', 'Costa Rica',
       'Caribbean small states', 'Cuba', 'Curacao', 'Cayman Islands',
       'Cyprus', 'Czech Republic', 'Germany', 'Djibouti', 'Dominica',
       'Denmark', 'Dominican Republic', 'Algeria',
       'East Asia & Pacific (excluding high income)',
       'Early-demographic dividend', 'East Asia & Pacific',
       'Europe & Central Asia (excluding high income)',
       'Europe & Central Asia', 'Ecuador', 'Egypt, Arab Rep.',
       'Euro area', 'Spain', 'Estonia', 'Ethiopia', 'European Union',
       'Fragile and conflict affected situations', 'Finland', 'Fiji',
       'France', 'Faroe Islands', 'Gabon', 'United Kingdom', 'Georgia',
       'Ghana', 'Gibraltar', 'Guinea', 'Gambia, The', 'Guinea-Bissau',
       'Equatorial Guinea', 'Greece', 'Grenada', 'Greenland', 'Guatemala',
       'Guam', 'Guyana', 'High income', 'Hong Kong SAR, China',
       'Honduras', 'Heavily indebted poor countries (HIPC)', 'Croatia',
       'Haiti', 'Hungary', 'IBRD only', 'IDA & IBRD total', 'IDA total',
       'IDA blend', 'Indonesia', 'IDA only', 'Isle of Man', 'India',
       'Ireland', 'Iran, Islamic Rep.', 'Iraq', 'Iceland', 'Israel',
       'Italy', 'Jamaica', 'Jordan', 'Japan', 'Kazakhstan', 'Kenya',
       'Kyrgyz Republic', 'Cambodia', 'Kiribati', 'St. Kitts and Nevis',
       'Korea, Rep.', 'Latin America & Caribbean (excluding high income)',
       'Lao PDR', 'Lebanon', 'Liberia', 'Libya', 'St. Lucia',
       'Latin America & Caribbean',
       'Least developed countries: UN classification', 'Low income',
       'Liechtenstein', 'Sri Lanka', 'Lower middle income',
       'Low & middle income', 'Lesotho', 'Late-demographic dividend',
       'Lithuania', 'Latvia', 'Macao SAR, China',
       'St. Martin (French part)', 'Morocco', 'Monaco', 'Moldova',
       'Madagascar', 'Maldives', 'Middle East & North Africa', 'Mexico',
       'Middle income', 'North Macedonia', 'Mali', 'Malta', 'Myanmar',
       'Middle East & North Africa (excluding high income)', 'Montenegro',
       'Mongolia', 'Mozambique', 'Mauritania', 'Mauritius', 'Malawi',
       'Malaysia', 'North America', 'Namibia', 'New Caledonia', 'Niger',
       'Nigeria', 'Nicaragua', 'Netherlands', 'Norway', 'Nepal', 'Nauru',
       'New Zealand', 'OECD members', 'Oman', 'Other small states',
       'Pakistan', 'Panama', 'Peru', 'Philippines', 'Papua New Guinea',
       'Poland', 'Pre-demographic dividend', 'Puerto Rico',
       'Korea, Dem. People’s Rep.', 'Portugal', 'Paraguay',
       'Pacific island small states', 'Post-demographic dividend',
       'French Polynesia', 'Qatar', 'Romania', 'Russian Federation',
       'Rwanda', 'South Asia', 'Saudi Arabia', 'Senegal', 'Singapore',
       'Solomon Islands', 'Sierra Leone', 'El Salvador', 'San Marino',
       'Somalia', 'Sub-Saharan Africa (excluding high income)',
       'Sub-Saharan Africa', 'Small states', 'Sao Tome and Principe',
       'Suriname', 'Slovak Republic', 'Slovenia', 'Sweden', 'Eswatini',
       'Seychelles', 'Syrian Arab Republic', 'Turks and Caicos Islands',
       'Chad', 'East Asia & Pacific (IDA & IBRD countries)',
       'Europe & Central Asia (IDA & IBRD countries)', 'Togo', 'Thailand',
       'Tajikistan', 'Turkmenistan',
       'Latin America & the Caribbean (IDA & IBRD countries)',
       'Timor-Leste', 'Middle East & North Africa (IDA & IBRD countries)',
       'Tonga', 'South Asia (IDA & IBRD)',
       'Sub-Saharan Africa (IDA & IBRD countries)', 'Trinidad and Tobago',
       'Tunisia', 'Turkey', 'Tuvalu', 'Tanzania', 'Uganda', 'Ukraine',
       'Upper middle income', 'Uruguay', 'United States', 'Uzbekistan',
       'St. Vincent and the Grenadines', 'Venezuela, RB',
       'British Virgin Islands', 'Virgin Islands (U.S.)', 'Vietnam',
       'Vanuatu', 'World', 'Samoa', 'Kosovo', 'Yemen, Rep.',
       'South Africa', 'Zambia', 'Zimbabwe'], dtype=object)

In [11]:

def Diff(li1, li2): 
    '''
    # Python code t get difference of two lists 
    # Using set() 
    '''
    return (list(set(li1).symmetric_difference(set(li2))))

In [15]:
delta = Diff(consumption_countries, density_countries)
delta

['Slovak Republic',
 'Serbia',
 'Hawaiian Trade Zone',
 'Cook Islands',
 'East Asia & Pacific (excluding high income)',
 'U.S. Virgin Islands',
 'Low income',
 'Saint Lucia',
 'St. Vincent and the Grenadines',
 'Congo-Kinshasa',
 'Latin America & Caribbean (excluding high income)',
 'Bahamas, The',
 'Latin America & the Caribbean (IDA & IBRD countries)',
 'Burma',
 'IDA & IBRD total',
 'Iran',
 'OECD members',
 'Iran, Islamic Rep.',
 'Saint Vincent/Grenadines',
 'Yemen, Rep.',
 'Early-demographic dividend',
 'Europe & Central Asia (excluding high income)',
 'Former Czechoslovakia',
 'Upper middle income',
 'Middle East & North Africa (excluding high income)',
 'Western Sahara',
 'Middle income',
 'Egypt',
 'Middle East & North Africa (IDA & IBRD countries)',
 "Cote d'Ivoire",
 'Lao PDR',
 'Low & middle income',
 'Heavily indebted poor countries (HIPC)',
 'Small states',
 'Other small states',
 'Luxembourg',
 'Kuwait',
 'Côte d’Ivoire',
 'Euro area',
 'European Union',
 'IBRD only',
 'Kyrgyzstan',
 'French Guiana',
 'Hong Kong',
 'Belgium',
 'Sub-Saharan Africa (IDA & IBRD countries)',
 'Laos',
 'Sudan',
 'Macau',
 'U.S. Territories',
 'Former U.S.S.R.',
 'Virgin Islands (U.S.)',
 'IDA total',
 'North America',
 'Andorra',
 'Fragile and conflict affected situations',
 'Eritrea',
 'South Sudan',
 'Curacao',
 'IDA blend',
 'Congo-Brazzaville',
 'Europe & Central Asia',
 'Micronesia',
 'Arab World',
 'Reunion',
 'Channel Islands',
 'Montserrat',
 'Hong Kong SAR, China',
 'Martinique',
 'Venezuela, RB',
 'Central Europe and the Baltics',
 'Venezuela',
 'Liechtenstein',
 'The Bahamas',
 'East Asia & Pacific (IDA & IBRD countries)',
 'Least developed countries: UN classification',
 'Late-demographic dividend',
 'North Korea',
 'South Asia (IDA & IBRD)',
 'Brunei',
 'Kyrgyz Republic',
 'Palestinian Territories',
 'Congo, Dem. Rep.',
 'Northern Mariana Islands',
 'Netherlands Antilles',
 'Isle of Man',
 'Former Serbia and Montenegro',
 'Wake Island',
 'South Korea',
 'Latin America & Caribbean',
 'Russia',
 'Korea, Rep.',
 'Former Yugoslavia',
 'High income',
 'Syrian Arab Republic',
 'Germany, West',
 'Germany, East',
 'East Asia & Pacific',
 'St. Martin (French part)',
 'Caribbean small states',
 'Macao SAR, China',
 'Sub-Saharan Africa',
 'Egypt, Arab Rep.',
 'Lower middle income',
 'Post-demographic dividend',
 'Saint Helena',
 'Slovakia',
 'Korea, Dem. People’s Rep.',
 'St. Kitts and Nevis',
 'Taiwan',
 'Congo, Rep.',
 'IDA only',
 'Russian Federation',
 'Falkland Islands',
 'Guadeloupe',
 'Brunei Darussalam',
 'St. Lucia',
 'Monaco',
 'Pre-demographic dividend',
 'South Asia',
 'Yemen',
 'Niue',
 'Myanmar',
 'Middle East & North Africa',
 'Antarctica',
 'U.S. Pacific Islands',
 'Sub-Saharan Africa (excluding high income)',
 'Syria',
 'Pacific island small states',
 'Europe & Central Asia (IDA & IBRD countries)',
 'Saint Kitts and Nevis',
 'Saint Pierre and Miquelon',
 'San Marino']

In [10]:
'''
what questions do we want to answer?
'''

'\nwhat questions do we want to answer?\n'